server:
  port: 8001
#  servlet:
#    context-path: /api
spring:
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
#  配置redis
  redis:
    host: localhost
    port: 6379
#    缓存
  cache:
    type: redis
#  rabiitMq配置
  rabbitmq:
    host: 39.108.176.143
    port: 5672
    username: river
    password: 123123
    virtual-host: /
    listener:
      simple:
        prefetch: 1 #预取数

# 配置mybatisplus
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id #主键为雪花算法
  configuration: #控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#日志
#logging:
#  logback:
#    rollingpolicy:
#      max-file-size: 3KB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
#  level:
#    root: debug

#缓存前缀
cache-prefix:
  #验证码
  register-key: verification

#jwt密钥
jwt:
  online: river